openapi: 3.1.0
info:
  version: 1.0.0
  title: Money Guard App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Money Guard
tags:
  - name: Auth
    description: Operations about authentication.
  - name: Users
    description: Operations about users.
  - name: Transactions
    description: Operations about transactions.
  - name: Categories
    description: Operations about categories.
  - name: Summary
    description: Operations about summary statistics.
servers:
  - url: http://localhost:3000
  - url: https://nightcodestudio-backend.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
